services:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=amg
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - "${AMG_VOL_PATH}:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    restart: unless-stopped
  
  backend:
    depends_on:
      - database
    image: amg-time-backend
    build: ./amg_time
    ports:
      - 8000:8000
    restart: unless-stopped
  
  front:
    depends_on: 
      - backend
    image: amg-time-frontend
    build: ./amg_time_front
    ports:
      - 3000:3000
    restart: unless-stopped