# Generated by Django 5.1.4 on 2025-03-13 14:48

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(default='Полное имя', editable=False, max_length=150, null=True, verbose_name='Полное имя')),
                ('surname_name', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, null=True, verbose_name='Отчество')),
                ('department', models.CharField(choices=[('OV', 'ОВ'), ('VK', 'ВК'), ('SS', 'СС'), ('El', 'ЭОМ')], max_length=3, null=True, verbose_name='Отдел')),
                ('role', models.CharField(choices=[('User', 'Пользователь'), ('Admin', 'Админ')], max_length=13, null=True, verbose_name='Роль')),
                ('salary', models.FloatField(default=0, max_length=15, verbose_name='Оклад')),
                ('hour_revenue', models.FloatField(default=0, max_length=15, verbose_name='Ставка (заполняется автоматически)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_year', models.IntegerField(default=2025)),
                ('inv_number', models.CharField(blank=True, max_length=10, verbose_name='Номер накладной')),
                ('date', models.DateField(default=datetime.datetime(2025, 3, 13, 14, 48, 22, 251641, tzinfo=datetime.timezone.utc), verbose_name='Дата')),
                ('inv_number_int', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='amg_time.employee', verbose_name='Сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.IntegerField(verbose_name='N')),
                ('description', models.CharField(max_length=500, verbose_name='Наименование документации')),
                ('quantity', models.IntegerField(verbose_name='Кол-во экземпляров')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amg_time.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название/Адрес')),
                ('prj_number', models.CharField(max_length=200, verbose_name='Номер договора')),
                ('date', models.DateField(default=datetime.datetime(2025, 3, 13, 14, 48, 22, 250895, tzinfo=datetime.timezone.utc), verbose_name='Дата')),
                ('price', models.FloatField(default=0, max_length=20, verbose_name='Сумма')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивный')),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='amg_time.customer', verbose_name='Заказчик')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amg_time.project', verbose_name='Проект'),
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.FloatField(default=0, max_length=20, verbose_name='Сумма')),
                ('diplay_name', models.CharField(editable=False, max_length=500, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amg_time.project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agr_number', models.CharField(max_length=200, verbose_name='Номер')),
                ('price', models.FloatField(default=0, max_length=20, verbose_name='Сумма')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='amg_time.project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(max_length=200, null=True, verbose_name='Номер акта')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('price', models.FloatField(default=0, max_length=20, verbose_name='Сумма')),
                ('date', models.DateField(default=datetime.datetime(2025, 3, 13, 14, 48, 22, 251439, tzinfo=datetime.timezone.utc), verbose_name='Дата')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amg_time.project', verbose_name='Проект')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2025, 3, 13, 14, 48, 22, 252007, tzinfo=datetime.timezone.utc), verbose_name='Дата')),
                ('time_spent', models.FloatField(max_length=6, verbose_name='Затраченное время')),
                ('costs', models.FloatField(blank=True, editable=False, max_length=10, verbose_name='Затраты')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Описание')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amg_time.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
    ]
