# Generated by Django 5.1.4 on 2025-03-13 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amg_time', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачен'),
        ),
        migrations.AlterField(
            model_name='act',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 13, 14, 49, 8, 378628, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('OV', 'ОВ'), ('OViK', 'ОВиК'), ('VK', 'ВК'), ('SS', 'СС'), ('El', 'ЭОМ'), ('ITR', 'ИТР'), ('BIM', 'БИМ')], max_length=6, null=True, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 13, 14, 49, 8, 378833, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 13, 14, 49, 8, 378063, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 13, 14, 49, 8, 379200, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
