# Generated by Django 5.1.4 on 2025-03-18 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amg_time', '0002_act_is_paid_alter_act_date_alter_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 14, 45, 48, 431177, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 14, 45, 48, 431541, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 14, 45, 48, 430166, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
