# Generated by Django 5.1.4 on 2025-03-18 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amg_time', '0003_alter_act_date_alter_invoice_date_alter_project_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 14, 48, 17, 994283, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 14, 48, 17, 994655, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 18, 14, 48, 17, 993241, tzinfo=datetime.timezone.utc), verbose_name='Дата'),
        ),
    ]
