# Generated by Django 5.1.4 on 2025-03-18 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amg_time', '0004_alter_act_date_alter_invoice_date_alter_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата'),
        ),
    ]
