# Generated by Django 5.1.4 on 2025-04-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amg_time', '0005_alter_act_date_alter_invoice_date_alter_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('OV', 'ОВ'), ('OViK', 'ОВиК'), ('VK', 'ВК'), ('SS', 'СС'), ('El', 'ЭОМ'), ('ITR', 'ИТР'), ('BIM', 'БИМ')], max_length=7, null=True, verbose_name='Отдел'),
        ),
    ]
