# Generated by Django 5.1.4 on 2025-05-14 08:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amg_time', '0006_alter_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(max_length=200, null=True, verbose_name='Номер акта')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('price', models.FloatField(default=0, max_length=20, verbose_name='Сумма')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amg_time.contractor', verbose_name='Подрядчик')),
            ],
        ),
    ]
